name: global_repository
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0

  get: ^4.1.3
  signale:
    git: https://github.com/Nightmare-MY/signale
  # 提供路径访问
  # 事件总线
  event_bus: ^1.1.0
  permission_handler: 6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icon/
