name: global_repository
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  synchronized: ^3.0.0

  responsive_framework: ^0.2.0
  signale: ^0.0.6
  # 提供路径访问
  permission_handler: 6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icon/
